---
- hosts: all
  gather_facts: false
  tasks:
    - name: Install Python
      ansible.builtin.raw: |
        apt-get update
        apt-get -y install ca-certificates python3
      changed_when: false
      failed_when: false

    - name: Call setup
      ansible.builtin.setup:

- hosts: test-kubectl-1804,test-kubectl-2004,test-kubectl-2204
  vars_files:
    - vars/ubuntu.yml
  tasks:
    - name: Include kubectl role
      ansible.builtin.include_role:
        name: githubixx.kubectl

- hosts: test-kubectl-debian10,test-kubectl-debian11
  tasks:
    - name: Include kubectl role
      ansible.builtin.include_role:
        name: githubixx.kubectl
