---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .

platforms:
  - name: test-ubuntu-2004
    image: ubuntu:20.04
    pre_build_image: true
  - name: test-ubuntu-1804
    image: ubuntu:18.04
    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: ansible
