---
# Copyright (C) 2026 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Verify setup
  hosts: all
  vars:
    expected_output: "v1.33.8"
  tasks:
    - name: Execute kubectl version to capture output
      ansible.builtin.command: kubectl version --client=true
      register: kubectl_version_output
      changed_when: false

    - name: Ensure kubectl version output contains correct version string
      ansible.builtin.assert:
        that:
          - "expected_output in kubectl_version_output.stdout"
